[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "wagon butter blue lunar document run maximum soul delay field protect churn unlock afraid soup arrest syrup nest stadium office lumber approve popular tail"
